### ISSUE TITLE
Inifinite breath

### ISSUE THREAD

**Issue by mazes-80** [FaceDeer/airtanks#6]
You can breath underwater even using empty tanks.
I don't know exactly which commit offered this nice behavior, but it's quite recent.
I'll may try to bisect.

**Comment by FaceDeer** [comment]
Is this issue with the [mineclone compatibility](https://github.com/minetest-mods/airtanks/tree/mineclone_compatibility) branch? I haven't merged that into the master branch yet, fortunately. :) I'm on vacation for the next few days with no access to my home computer, so no rush isolating the cause - I can't do anything until I get back. Thanks for letting me know about it, I'll definitely make sure I can drown before releasing this update.

**Comment by mazes-80** [comment]
Nothing related to mineclone branch, it just happens in minetest_game.
Have good vacation. I'll steel try to take a look to what happens, but
low rank on my todo list as infinite breath is quite nice.

**Comment by FaceDeer** [comment]
Huh, that's weird. The master branch hasn't had a commit in two years, it must be a result of a change in minetest_game or Minetest itself.

I'll still hop right on testing and fixing it when I get back, though. This mod is supposed to make long underwater excursions possible, but not trivial. *Some* resource management should be required. :)

**Comment by mazes-80** [comment]
Think your commit fixes it. No more infinite breath.
